[server]
ip = "0.0.0.0"
port = 4001

[database]
url = "postgres://postgres@localhost:5432/kythi" # self-explanatory

[redis]
url = "redis://127.0.0.1:6379" # self-explanatory

[logger]
level = 5                  # TODO: add documentation for log level
output_file = "output.log" # file where logs are saved

[identity]
secret = ""      # 256 byte string of alphanumeric characters
deadline = 86400 # basically expiration, given in seconds, i recommend 24 hours min
